### PR TITLE
Set up a "Hello world" project with two apps

### PR DESCRIPTION
**Pull request by Kashif-Saleem-Ghuman**
Hi Code Reviewer 👋
 
🟢 In this milestone
- [ ] Project requirements
  - [ ] Create a new Rails API app called 'hello-rails-back-end'.
  - [ ] Initialize your project with Git.
  - [ ] Make sure that your project has a Postgres database set up.
  - [ ] Create a table for storing your messages and create 5 different greetings.
  - [ ] Create an API endpoint that selects a random greeting from your table (you will need a controller with an action and rails route).
[LInk to front end repo](https://github.com/Kashif-Saleem-Ghuman/hello-react-front-end/tree/project)
[LInk to front end repo PR](https://github.com/Kashif-Saleem-Ghuman/hello-react-front-end/pull/1)

### CODE REVIEW

**Review by Olamarx — CHANGES_REQUESTED** [review]
Hi @Kashif-Saleem-Ghuman, 

While you made a great effort in this project, unfortunately, I cannot proceed to review your code.

## Invalid Code Review Request

You have submitted a project, that has no future features, kindly add it as it is a required section on the readme file.

Your Code Review Request will be marked as invalid in your Dashboard, so please submit a new one once you are ready 🙏

Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Please, remember to tag me in your question so I can receive the notification.

**_Please, do not open a new Pull Request for re-reviews. You should use the same Pull Request submitted for the first review, either valid or invalid unless it is requested otherwise._**

--------

_Invalid Code Review Request **does not count** into the code reviews limit._

**Comment by Kashif-Saleem-Ghuman** [comment]
@Olamarx Thank you for your feedback. 🙏  I have added the future features section now.

**Review by FrederickMih — APPROVED** [review]
## Hi :raising_hand:  @Kashif-Saleem-Ghuman, 

Your project is complete!  There is nothing else to say other than... it's time to merge it :shipit: 
Congratulations! 🎉 



## Highlights :green_circle: 

- PR is professional :+1: 
- The two apps connect together :+1: 
- Linter checks passed :heavy_check_mark: 

## Optional suggestions
**N/A**

_Every comment with the [OPTIONAL] prefix won't stop the approval of this PR. However, I strongly recommend you to take them into account as they can make your code better. Some of them were simply missed by the previous reviewer and addressing them will really improve your application._

Cheers, and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Please, remember to tag me in your question so I can receive the notification.

------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561)  you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

**Comment by Kashif-Saleem-Ghuman** [comment]
@FrederickMih Thank you for approving my PR 🙏

**Pull request merged**
